version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: alireza
      POSTGRES_PASSWORD: 2873
    ports:
      - "5432:5432"
  
  image_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IMAGE_NAME: "your_search_query_here"
      MAX_IMAGE: 10
    depends_on:
      - postgres
